language: node_js
node_js:
  - "11.1.0"

sudo: false

script:
  - bash scripts/ci.sh

deploy:
  fqdn: dot2array.taxio.me
  provider: pages
  local-dir: ./webapp/build
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

